### PR TITLE
Try to fix https://github.com/webdriverio/wdio-allure-reporter/issues/26

### PR DESCRIPTION
**Pull request by IlgizVafin**
+ add "test:pending" handler

### CODE REVIEW

**Comment by just-boris** [comment]
Good!

To be sure that this fix actually have an effect, could you please add a test with `peding` example.
You can find an example in this file: https://github.com/webdriverio/wdio-allure-reporter/blob/master/test/specs/test-case.js#L7

**Comment by IlgizVafin** [comment]
@just-boris check please test for pending status.

I think there is something wrong:
image

Could you help me?

**Comment by just-boris** [comment]
Well, it seems like pending test case doesn't fire `test:start` event.

So, there is a special method `allure.pendingCase` ([source code](https://github.com/allure-framework/allure-js-commons/blob/master/index.js#L82)), that you should use to report pending test cases.

**Comment by IlgizVafin** [comment]
@just-boris now

**Comment by christian-bromann** [comment]
@just-boris can you approve this?

**Comment by just-boris** [comment]
Yes, I will.

I am going to run this locally to be sure that everything works as expected. Probably this will be today or tomorrow.

**Pull request merged**
