### PR TITLE
Handle case when wdio tests run against multiply browsers

### PR DESCRIPTION
**Pull request by BorisOsipov**
Fix for https://github.com/webdriverio/wdio-allure-reporter/issues/103

Test in report will look like -

### CODE REVIEW

**Comment by baev** [comment]
Is the `test.cid` the same between runs? If not history features will not work. 

You can add the browser as test parameter to each test, that will fix the issue without changing the names

**Comment by BorisOsipov** [comment]
@baev Thank you for your review. 

>Is the test.cid the same between runs? If not history features will not work
yes it maybe the same and probably break history feature.

> You can add the browser as test parameter to each test, that will fix the issue without changing the names
Will it work for allure1 too? if yes I definitely follow your advice.

**Comment by baev** [comment]
> Will it work for allure1 too?

yep, Allure 1 has no retries support, so everything will be fine

**Comment by BorisOsipov** [comment]
@baev Thanks I will check and change this PR.

**Comment by BorisOsipov** [comment]
@baev 

>You can add the browser as test parameter to each test, that will fix the issue without changing the names

I've added browser as parameter and generated data for report
[Xml1](https://gist.github.com/BorisOsipov/fa09f13027b3ca91a0a1184661b8934b)
[Xml2](https://gist.github.com/BorisOsipov/08c5eaf8184fc49936d32f4959b7b40b)

But in a report there is only one test and one retry for this test(it is original issue we try to solve)
image

What did I do wrong?

**Comment by baev** [comment]
change parameter kind to `argument`

**Comment by BorisOsipov** [comment]
@baev Awesome! Thank you a lot for you help 👍

image

**Comment by christian-bromann** [comment]
Published as `v0.5.1`

**Pull request merged**
