### PR TITLE
Add test reproducing empty values in xml

### PR DESCRIPTION
**Pull request by just-boris**
This is a reproduction for issue https://github.com/webdriverio/wdio-allure-reporter/issues/29

Currently it fails, but I hope to come up with some solution later

### CODE REVIEW

**Comment by christian-bromann** [comment]
@just-boris what's the state of this?

**Comment by just-boris** [comment]
Couldn't find any better solution.

So far, there is a new 2.0 version of Allure: https://github.com/allure-framework/allure2
It will change data format from XML to JSON and also will become more tolerant to such problems. maybe that will be a solution. As soon as it will be stable enough, I will send a PR, that upgrades code to be working with Allure 2

**Comment by timbru31** [comment]
According to the milestone/project of Allure, due date for v2 is 04/30/2017: https://github.com/allure-framework/allure2/milestone/4

**Comment by just-boris** [comment]
Not sure about actual release tomorrow, but there is already a beta version, that you can try

```
npm install allure-commandline@beta
```

I have been using this for a week, it is quite stable. Also check, that your `node_modules` has `allure-js-commons@1.3.0` or above. I have released a new version there, that adds v2 support (in a backward-compatible way though).

**Comment by christian-bromann** [comment]
@just-boris what's the status of this?

**Comment by christian-bromann** [comment]
Closing due to inactivity.

**Pull request closed without merging**
