### PR TITLE
Update README with docs for story feature

### PR DESCRIPTION
**Pull request by art-tykh**

### CODE REVIEW

**Comment by netmajor** [comment]
You could also change it.only to it. But I done it already in my PR .
Now only your test is executed :/

**Comment by christian-bromann** [comment]
@art-tykh could you please resolve the conflict or is this PR already outdated?

**Comment by netmajor** [comment]
@art-tykh Hi, Did you test our new allure API like your story, in real test project ? I have problem how to access this api in runtime.js :/

**Comment by art-tykh** [comment]
@netmajor  Yeap, I am using new allure API on my current project. You need to import runtime.js by direct path to use it. Something like this:
`const allure = require('./node_modules/wdio-allure-reporter/build/runtime');`

**Comment by netmajor** [comment]
Yes, I try to use our new api in my app and your solution is not so good :/ i forgot to check this. My bad : /  I need to fix this and add index.js

**Comment by christian-bromann** [comment]
I think this can be closed now

**Pull request closed without merging**
